import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("EducationDataset_2023-24.csv")
district = "District"
schools = "No of Schools - Total"
students = "No of Students - Total"
boys = "No of Students - Boys"
girls = "No of Students - Girls"
class_x = " PASS PERCENTAGE IN CLASS X - \n(Before Compt.) - 2023-24"
class_xii = "PASS PERCENTAGE IN CLASS XII - (Before Compt.) - 2023-24"
print("\nQ1:", df.loc[df[schools].idxmax(), district], "->", df[schools].max())
print("   ", df.loc[df[schools].idxmin(), district], "->", df[schools].min())
index = df[students].idxmax()
print("\nQ2:", df.loc[index, district], "->", df.loc[index, students])
df["Gender Difference"] = abs(df[boys] - df[girls])
index = df["Gender Difference"].idxmax()
print("\nQ3:", df.loc[index, district], "->", df.loc[index, "Gender Difference"])
print("\nQ4:", df.loc[df[class_x].idxmax(), district], "->", df[class_x].max(), "%")
print("Q5:", df.loc[df[class_xii].idxmax(), district], "->", df[class_xii].max(), "%")
df["XII - X"] = df[class_xii] - df[class_x]
print("\nQ6 Average Class X:", df[class_x].mean())
print("   Average Class XII:", df[class_xii].mean())
print(df[[district, class_x, class_xii, "XII - X"]])
schools_pass_correlation = np.corrcoef(df[schools], df[class_x])[0, 1]
print("\nQ7 Correlation:", schools_pass_correlation)
plt.figure(figsize=(9, 5))
plt.scatter(df[schools], df[class_x], s=70, alpha=0.8)
plt.xlabel("Number of Schools")
plt.ylabel("Class X Pass Percentage")
plt.title("Schools vs Class X Pass Percentage")
plt.grid(alpha=0.25)
plt.tight_layout()
plt.show()
enrollment_pass_correlation = np.corrcoef(df[students], df[class_x])[0, 1]
print("\nQ8 Correlation:", enrollment_pass_correlation)
plt.figure(figsize=(9, 5))
plt.scatter(df[students], df[class_x], s=70, alpha=0.8)
plt.xlabel("Total Student Enrollment")
plt.ylabel("Class X Pass Percentage")
plt.title("Enrollment vs Class X Pass Percentage")
plt.grid(alpha=0.25)
plt.tight_layout()
plt.show()
df["Students per School"] = df[students] / df[schools]
index = df["Students per School"].idxmax()
students_per_school_correlation = np.corrcoef(df["Students per School"], df[class_x])[0, 1]
print("\nQ9:", df.loc[index, district], "->", df.loc[index, "Students per School"])
print("   Correlation:", students_per_school_correlation)
plt.figure(figsize=(9, 5))
plt.scatter(df["Students per School"], df[class_x], s=70, alpha=0.8)
plt.xlabel("Students per School")
plt.ylabel("Class X Pass Percentage")
plt.title("Students per School vs Class X Pass Percentage")
plt.grid(alpha=0.25)
plt.tight_layout()
plt.show()
plt.figure(figsize=(12, 5))
plt.bar(df[district], df[schools], alpha=0.8)
plt.xticks(rotation=45, ha="right")
plt.ylabel("Number of Schools")
plt.title("Number of Schools by District")
plt.grid(axis="y", alpha=0.25)
plt.tight_layout()
plt.show()
x = np.arange(len(df))
plt.figure(figsize=(12, 5))
plt.bar(x - 0.2, df[class_x], 0.4, label="Class X")
plt.bar(x + 0.2, df[class_xii], 0.4, label="Class XII")
plt.xticks(x, df[district], rotation=45, ha="right")
plt.ylabel("Pass Percentage")
plt.title("Class X vs Class XII Pass Percentage")
plt.legend()
plt.grid(axis="y", alpha=0.25)
plt.tight_layout()
plt.show()
plt.figure(figsize=(9, 5))
plt.scatter(df["Students per School"], df[class_x], s=70, alpha=0.8)
plt.xlabel("Students per School")
plt.ylabel("Class X Pass Percentage")
plt.title("Students per School vs Class X Pass Percentage")
plt.grid(alpha=0.25)
plt.tight_layout()
plt.show()